services:
  nats: 
    image: nats:latest
    ports:
      - "4222:4222"
    command: "--server_name tours -js -sd /data --cluster_name nats --cluster nats://0.0.0.0:6222 --http_port 8222 "
    volumes:
      - "./nats-jetstream:/data"

  # APi Products
  toursapi: 
    container_name: toursapi
    restart: always
    build: 
      context: ./microservices/api-tour/
      dockerfile: Dockerfile
    external_links:
      - mongo
    environment:
      - MONGO_HOST=mongotours
      - MONGO_DB=tours
      - MONGO_PORT=27017
      - LOCAL_PORT=8081
      - NATS_HOST=demo.nats.io
      - NATS_PORT=4222
    depends_on:
      - nats

  # API Search
  searchapi: 
    container_name: searchapi
    restart: always
    build: 
      context: ./microservices/api-search/
      dockerfile: Dockerfile
    external_links:
      - mongo
    environment:
      - MONGO_HOST=mongosearch
      - MONGO_DB=dbsearch
      - MONGO_PORT=27017
      - LOCAL_PORT=8082
      - NATS_HOST=demo.nats.io
      - NATS_PORT=4222
    depends_on:
      - nats
    
  
  # Data Base Products
  mongotours:
    container_name: db-mongotours
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: dbtours
    ports:
      - '27018:27017'
    volumes:
        - mongo-tours-vl:/data:/data/db 
    command: mongod --quiet --logpath /dev/null


  # Data Base Search 
  mongosearch:
    container_name: db-mongosearch
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: dbsearch
    volumes:
        - mongo-search-vl:/data:/data/db 
    ports:
      - '27017:27017'
    command: mongod --quiet --logpath /dev/null
    depends_on:
      - nats

  lb:
    image: haproxy
    ports:
      - "80:80"
    volumes:
      - ./microservices/haproxy:/usr/local/etc/haproxy

# Volumes
volumes:
  mongo-search-vl:
  mongo-tours-vl: